# 创建ndarray数组

In [1]:
# 将列表转换为 ndarray

import numpy as np

data1 =[5,7,9,20]

arr1 = np.array(data1)
arr1

array([ 5,  7,  9, 20])

In [2]:
# 将元组转换为 ndarray
data2 =(1,3,5,7)
arr2 = np.array(data2)
arr2

array([1, 3, 5, 7])

In [3]:
# 将二维数组转换为 ndarray
data3 =[[1,3,5,7],
        [2,4,6,8]]

arr3 =np.array(data3)
arr3

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

# arange()函数


In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# ndarray数据类型

In [ ]:
arr