In [1]:
import numpy as np

# 列表
data1 = [1,2,3,4]
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4])

In [2]:
# 元组
data2 = (1,2,3,4)
arr2 = np.array(data2)
arr2

array([1, 2, 3, 4])

In [3]:
# 多维数组
data3 = [[1,2,3,4],[5,6,7,8]]   
arr3 = np.array(data3)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Series

Pandas Series 类似表格中的一个列（column），类似于一维数组，可以保存任何数据类型。

In [4]:
import pandas as pd

a=[1,2,3]

data =pd.Series(a)
data

0    1
1    2
2    3
dtype: int64

In [5]:
# 指定索引

a=['C','java','python']

data =pd.Series(a,index=['one','two','three'])
data

one           C
two        java
three    python
dtype: object

In [6]:
# 通过字典创建Series,字典的 key 变成了索引值。

a={
    1:'C',
    2:'java',
    3:'python'
}

data=pd.Series(a)
data

1         C
2      java
3    python
dtype: object