### numpy

#### 1. 简介
    * ndarray，一个具有矢量算术运算和复杂广播能力的快速且节省空间的多维数组。
    * 高效处理大数组的数据
    * NumPy可以在整个数组上执行复杂的计算，而不需要Python的for循环。

#### 2. 构建数组

In [2]:
import numpy as np #导入numpy库

1. list 转化为 array 

In [3]:
list01 = [1,3,5,7]
array01=np.array(list01)

print(array01)
type(array01)

[1 3 5 7]


numpy.ndarray

2. 构建随机数组

In [4]:
# 构建随机样本位于[0, 1)中
np.random.rand()

0.7424476256602698

In [5]:
np.random.rand(3,2)

array([[0.46991169, 0.90854307],
       [0.89406852, 0.35757138],
       [0.92881671, 0.16936573]])

In [6]:
# 构建正态分布随机数组
array02=np.random.randn(10000)
array02

array([-0.21824884, -1.76738929, -0.91907933, ...,  0.02914031,
        0.25642738,  1.75425883])

np.random.normal(loc=0.0,scale=1.0,size=None)

随机生成高斯分布的样本

参数：

loc：float类型，均值

scale：float类型，标准差

size：int或tuple of int类型，样本规模

In [8]:
def softmax(x):
    x_row_max = x.max(axis=-1)
    x_row_max = x_row_max.reshape(list(x.shape)[:-1]+[1])
    x = x - x_row_max
    x_exp = np.exp(x)
    x_exp_row_sum = x_exp.sum(axis=-1).reshape(list(x.shape)[:-1]+[1])
    softmax = x_exp / x_exp_row_sum
    return softmax

times=np.array([1,1,7,3])

prob=softmax(times)

print(prob)
print(np.sum(prob))

[0.00242238 0.00242238 0.97725618 0.01789907]
0.9999999999999999


随机整数

np.random.randint(1,5)

np.random.randint(1,5,size=10)

np.random.randint(1,5,size=(3,5))

shuffle(x) 现场修改序列，改变自身内容。（类似洗牌，打乱顺序）

In [9]:
array03=np.array([1,2,3,4,5])
np.random.shuffle(array03)

In [10]:
array03

array([5, 3, 2, 1, 4])

随机挑选

In [1]:
import numpy as np
np.random.choice(100,5)
# np.random.choice(range(100,200),5)

array([70, 15, 12, 79, 39])

#### 随机种子

In [2]:
# 定义全局种子
np.random.seed(121)
np.random.rand(3)

np.random.choice(5,3)

In [3]:
# 定义局部种子
prng = np.random.RandomState(123456789) 
prng.rand(3)

array([0.53283302, 0.5341366 , 0.50955304])

3. 构建整数数组

In [14]:
np.arange(10)
np.arange(3,10)
np.arange(10).reshape(2,5)
np.linspace(0, 2, 100) # 0-2 之间均匀分布的100个数

array([0.        , 0.02020202, 0.04040404, 0.06060606, 0.08080808,
       0.1010101 , 0.12121212, 0.14141414, 0.16161616, 0.18181818,
       0.2020202 , 0.22222222, 0.24242424, 0.26262626, 0.28282828,
       0.3030303 , 0.32323232, 0.34343434, 0.36363636, 0.38383838,
       0.4040404 , 0.42424242, 0.44444444, 0.46464646, 0.48484848,
       0.50505051, 0.52525253, 0.54545455, 0.56565657, 0.58585859,
       0.60606061, 0.62626263, 0.64646465, 0.66666667, 0.68686869,
       0.70707071, 0.72727273, 0.74747475, 0.76767677, 0.78787879,
       0.80808081, 0.82828283, 0.84848485, 0.86868687, 0.88888889,
       0.90909091, 0.92929293, 0.94949495, 0.96969697, 0.98989899,
       1.01010101, 1.03030303, 1.05050505, 1.07070707, 1.09090909,
       1.11111111, 1.13131313, 1.15151515, 1.17171717, 1.19191919,
       1.21212121, 1.23232323, 1.25252525, 1.27272727, 1.29292929,
       1.31313131, 1.33333333, 1.35353535, 1.37373737, 1.39393939,
       1.41414141, 1.43434343, 1.45454545, 1.47474747, 1.49494

4. 构建特殊数组

In [15]:
np.eye(4)
np.ones((3,4))
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

5. 查看数组信息

    array.shape
    
    array.ndim
    

6. 数组变形

    array.reshape()
    
    array.flatten()

In [16]:
np.arange(12).reshape(3,-1).flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])