# flatten()函数用法

flatten是numpy.ndarray.flatten的一个函数，即返回一个一维数组。

flatten只能适用于numpy对象，即array或者mat，普通的list列表不适用！。

a.flatten()：a是个数组，a.flatten()就是把a降到一维，默认是按行的方向降 。

In [15]:
import numpy as np
import pandas as pd

# 创建二维数组
a = np.array([[1, 2,3],
            [ 4,5,6],
            [7,8,9]]
            )

# 把二维数组降成一维数组
b = a.flatten()
print(b)



[1 2 3 4 5 6 7 8 9]


In [18]:
x=[1,2,3,4,5,6,7,8,9,10,11,12]
x1=np.array(x)
# print(x1)
x2 = x1.reshape(-1,4)# (行，列)
print(x2) 

df=pd.DataFrame(x2)
df

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12